[package]
name = "charr_dylib"
version = "0.1.0"
authors = ["runbmp"]
edition = "2018"

[dependencies]
crossterm = "*"
components = { path = "../../components" }
charr = { path = "../../systems/charr" }

[lib]
crate-type = ["dylib"]
